apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240308003323.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240308003323.0.0+build.6aff574
  releaseNotes: |
    Release v20240308003323.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-07-03-2024-13-36-30-720049379/where-for-dinner-my-apps-bundle@sha256:c53d3f7d4c91371875a12a3658159c258994389e659ef5231e4fc5d17805a06e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

