apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-notify.my-apps.tap.20240308003441.0.0+build.6aff574
spec:
  refName: where-for-dinner-notify.my-apps.tap
  version: 20240308003441.0.0+build.6aff574
  releaseNotes: |
    Release v20240308003441.0.0+build.6aff574 of package where-for-dinner-notify.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-07-03-2024-13-36-30-720049379/where-for-dinner-notify-my-apps-bundle@sha256:ef0c5e675a021e055a59cabed73c3314c82a296f07abdf8e5170c31a2425ac0a
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

